### ISSUE TITLE
 bidname 规则修改

### ISSUE THREAD

**Issue by vlbos** [boscore/bos.contracts#11]
# 修改方案短账户名竞标基本准则
	* 根据短名长度分组级别（<4为一组，其他同一长度为一组）。 同一长度按出价排名；
	* 每24小时（onclock 出块时间为准）每一个长度排名前n名拍买成交（n为短名长度，n<4为n=1）。

修改规则

	* 同一组内 上次交易关闭时间一天时间后才继续处理
	* 同一组内 按最后竞拍时间超过24小时，按出价排名，取排名前n个（n为短名长度，n<4为n=1）
	* 同一组24小时内出价不参与排名
	每24小时（onclock 出块时间为准）检查每一组是否满足上述条件，满足则执行，
	执行后，更新检查时间。

#现有EOS实现短账户名竞拍功能
## eosio.system合约规则：

	* 	距离上一次全网短名成交已经超过24小时；
	* 	成交的短名需要在全网竞价中排名最高；
	* 	成交的短名需要有超过24小时无人再出价；
	* 	每次出价必须加价超过10%；
	* 	第一次成交将在EOS主网激活14天后开始；

### 在eosio.system.cpp上的bidname操作 ，用于注册您的出价。 它强制执行名称出价的若干规则：
	* 检查它是否真的是一个顶级后缀（类似顶级域名），没有“.”;
	* 拒绝其他token的代币符号而不是EOS;
	* 检查具有出价短名的帐户是否已存在;
	* 检查该短名的拍卖是否仍然开放；
	* 检查报价是否高于0，并且比之前的报价高出至少10％;
	* 投标人无法提高自己的出价；
	* 退出的投标人报价退款。

### 在producer_pay.cpp上的onblock上有一个每分钟运行的代码块并检查：
	* 主网激活14天后;
	* 如果上次短名拍卖成功关闭时间超过一天;
	* 如果当前最后一个竞拍的时间超过24小时 ;
	* 如果满足上述所有条件，设置新短名的关闭时间，并在拍卖出价表上将最高出价设置为负值 。 负值表示短名竞拍成功，已授于竞拍者。
	
   

### 在newaccount操作中，也在eosio.system.cpp上 ：
	* 	应用常见的新帐户规则，但检查帐户是否具有高级名称后缀;
	* 	如果是，请检查后缀的名称出价表;
	* 	如果该后缀的拍卖已经结束（负投标价值）且新帐户创建者帐户等于该后缀的最高出价者帐户，则仅允许新帐户创建。
	* 	在高级名称声明后，从出价表中删除出价。
	* 	因此，在声明优质名称帐户后，将为此帐户保留具有相应后缀的整个命名空间。
	* 	如果您拥有赢得的帐户（例如， eos高级名称），则只有您或您的代理人可以创建以.eos结尾的新帐户。
	* 	最多包含13个字符（包括点）仍然适用。 因此，优质名称越短，它可以创建更多的子帐户。

**Comment by Thaipanda** [comment]
so the logic of bidname change to:

if len(accountname) <= 3, only ONE accountname will be saled
if len(accountname) >3, len(accountname) accountnames will be saled

**Comment by xiangxn** [comment]
单位时间处理的事务消耗很大的，我建议不用分组了，直接取前N来成交.

**Comment by vlbos** [comment]
> 单位时间处理的事务消耗很大的，我建议不用分组了，直接取前N来成交.

非常好的建议，感谢。考虑一天bidname如果过多，遍历循环消耗会大。正在考虑限制取前100个进行分组或进一步把分组粒度变粗如分三个长度区间。分组目的是长度较长的账户名有机会竞拍成交，不与短账户名在同一价位上拼。我们会进一步测试性能消耗，来权衡方案。再次感谢
