### ISSUE TITLE
BUILD FAIL

### ISSUE THREAD

**Issue by lvgang214** [boscore/bos.contracts#31]
BOS build  安装成功，bos.cdt build  安装成功 ，执行 contracts的 build.sh  失败 ，错误信息如下：
CMake Error at /usr/local/eosio.cdt/lib64/cmake/eosio.cdt/eosio.cdt-config.cmake:5 (include):
  include could not find load file:

    EosioWasmToolchain
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)

CMake Error at CMakeLists.txt:23 (message):
  Found eosio.cdt version but it does not satisfy version requirements:
  version '' is invalid

  Please use eosio.cdt version 2.0.x

-- Configuring incomplete, errors occurred!
See also "/opt/bos.contracts/build/CMakeFiles/CMakeOutput.log".

**Comment by snowlybetter** [comment]
对cdt  git checkout v2.0.1，然后重新编译，在编译合约试试
