### ISSUE TITLE
build fail with bosio.cdt

### ISSUE THREAD

**Issue by maodaishan** [boscore/bos.contracts#57]
built and installed latest bosio.cdt
clone bos/contracts, do cmake and make.
some error happened, it's literally the same with https://github.com/EOSIO/eosio.contracts/issues/180, and its solution works. 
please fix it if possible. thanks.

**Comment by snowlybetter** [comment]
you can use master branch to build,maybe   solve

**Comment by vonhenry** [comment]
try run follow commands first, then compile as normal
$ git submodule deinit --all -f
$ git submodule update --init --recursive
then ensure the out of `$ git state` is clean

**Comment by snowlybetter** [comment]
> try run follow commands first, then compile as normal
> $ git submodule deinit --all -f
> $ git submodule update --init --recursive
> then ensure the out of `$ git state` is clean
is your os  ubuntu or centos?maybe use blow option 
```
git checkout v2.0.1
git submodule update --init --recursive
./build.sh
```

**Comment by snowlybetter** [comment]
maybe you can use docker image ,https://github.com/boscore/bos.cdt/blob/v2.0.2/docker/README.md

**Comment by maodaishan** [comment]
> try run follow commands first, then compile as normal
> $ git submodule deinit --all -f
> $ git submodule update --init --recursive
> then ensure the out of `$ git state` is clean

Thanks @vonhenry ,this works!
